// The roff interpreter: the requests that decide what text even *is*
// before any macro package sees it -- string and register definition,
// user-defined macros, conditionals, argument substitution.
//
// This is the part a "find the .SH lines" shortcut cannot fake. A page
// generated by pod2man opens with a page of `.de`, `.ie`, `.el` and `.ds`
// that define the macros the rest of the page is written in; a page that
// wasn't interpreted first would show that scaffolding as content and
// miss the content entirely.
//
// Output is a flat event stream -- a request the macro package should
// handle, or a line of text -- so `man.rs` can be about man(7) and
// nothing else. Termination is guaranteed by two budgets rather than by
// trusting the input: roff is Turing-complete, and a page is not a
// program this has any business running forever.

use std::collections::HashMap;
use std::ops::Range;

use super::lexer::{escape_len, is_comment_escape};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Event {
    // A request or macro this interpreter doesn't implement itself --
    // everything the macro package is for.
    Request { name: String, args: Vec<String>, span: Range<usize> },
    // One line of ordinary text, with strings and registers already
    // substituted and comments stripped. Font escapes are left in: they
    // are presentation, and belong to whatever builds the document.
    Text { text: String, span: Range<usize> },
}

// A line waiting to be processed, and where in the source it came from.
// A line from a macro body carries the span of the *invocation* -- that
// is the place a reader could point at, since the body itself may have
// been defined hundreds of lines earlier or not exist in the file at all.
#[derive(Debug, Clone)]
struct Line {
    text: String,
    span: Range<usize>,
}

struct Frame {
    lines: Vec<Line>,
    pos: usize,
    args: Vec<String>,
    name: String,
    // Whether these lines came from a macro body. It matters because a
    // body is stored verbatim: `\\$1` in the source is stored as
    // `\\$1`, and reducing that to `\$1` -- so the argument
    // substitution happens -- is what reading a body *does*.
    macro_body: bool,
}

// Enough for any real page, and small enough that a runaway `.while` or
// a macro that invokes itself stops being this program's problem.
const MAX_LINES: usize = 400_000;
const MAX_DEPTH: usize = 64;

pub struct Interp {
    strings: HashMap<String, String>,
    registers: HashMap<String, i64>,
    macros: HashMap<String, Vec<Line>>,
    frames: Vec<Frame>,
    // `.ie`'s result, for the `.el` that may follow it.
    conditions: Vec<bool>,
    processed: usize,
    pub notes: Vec<String>,
    pub events: Vec<Event>,
}

// Every event `source` produces, plus whatever this parse couldn't
// honour.
pub fn run(source: &str) -> (Vec<Event>, Vec<String>) {
    let mut interp = Interp::new();
    interp.push_source(source);
    interp.run();
    (interp.events, interp.notes)
}

impl Interp {
    fn new() -> Interp {
        let mut registers = HashMap::new();
        // The formatter-identifying registers a page branches on. bish
        // renders to a terminal, so it is nroff, and the .if n branch is
        // the one that should be taken.
        registers.insert("nl".to_string(), 0);
        registers.insert("$$".to_string(), 0);
        Interp {
            strings: HashMap::new(),
            registers,
            macros: HashMap::new(),
            frames: Vec::new(),
            conditions: Vec::new(),
            processed: 0,
            notes: Vec::new(),
            events: Vec::new(),
        }
    }

    fn push_source(&mut self, source: &str) {
        let mut lines = Vec::new();
        let mut start = 0;
        for (i, c) in source.char_indices() {
            if c == '\n' {
                lines.push(Line { text: source[start..i].to_string(), span: char_span(source, start, i) });
                start = i + 1;
            }
        }
        if start < source.len() {
            lines.push(Line { text: source[start..].to_string(), span: char_span(source, start, source.len()) });
        }
        self.frames.push(Frame { lines, pos: 0, args: Vec::new(), name: String::new(), macro_body: false });
    }

    fn note(&mut self, what: String) {
        if !self.notes.contains(&what) {
            self.notes.push(what);
        }
    }

    fn next_line(&mut self) -> Option<Line> {
        while let Some(frame) = self.frames.last_mut() {
            if frame.pos < frame.lines.len() {
                let line = frame.lines[frame.pos].clone();
                frame.pos += 1;
                return Some(line);
            }
            self.frames.pop();
        }
        None
    }

    fn run(&mut self) {
        while let Some(line) = self.next_line() {
            self.processed += 1;
            if self.processed > MAX_LINES {
                self.note("stopped: the page produced more output than any real page does".to_string());
                return;
            }
            self.process(line);
        }
    }

    fn process(&mut self, line: Line) {
        let in_macro = self.frames.last().is_some_and(|f| f.macro_body);
        let expanded = self.expand_in(&line.text, in_macro);
        let stripped = strip_comment(&expanded);
        let trimmed_control = control_start(&stripped);
        let Some(rest) = trimmed_control else {
            // Not a control line. A blank one is roff's own paragraph
            // break, which the macro package cares about.
            if stripped.trim().is_empty() && expanded.trim().is_empty() {
                self.events.push(Event::Request { name: "sp".to_string(), args: Vec::new(), span: line.span });
            } else {
                self.events.push(Event::Text { text: stripped, span: line.span });
            }
            return;
        };
        let (name, args_at) = request_name(&rest);
        if name.is_empty() {
            return;
        }
        let args_text = rest[args_at..].to_string();
        self.dispatch(&name, &args_text, line.span);
    }

    fn dispatch(&mut self, name: &str, args_text: &str, span: Range<usize>) {
        match name {
            // Definition and removal.
            "de" | "de1" | "am" | "am1" => self.define_macro(name.starts_with("am"), args_text),
            "ds" | "ds1" | "as" | "as1" => self.define_string(name.starts_with("as"), args_text),
            "nr" => self.set_register(args_text),
            "rr" => {
                for arg in split_args(args_text) {
                    self.registers.remove(&arg);
                }
            }
            "rm" => {
                for arg in split_args(args_text) {
                    self.macros.remove(&arg);
                    self.strings.remove(&arg);
                }
            }
            "rn" | "als" => {
                let args = split_args(args_text);
                if args.len() == 2 {
                    if let Some(body) = self.macros.get(&args[0]).cloned() {
                        self.macros.insert(args[1].clone(), body);
                    }
                    if let Some(value) = self.strings.get(&args[0]).cloned() {
                        self.strings.insert(args[1].clone(), value);
                    }
                    if name == "rn" {
                        self.macros.remove(&args[0]);
                        self.strings.remove(&args[0]);
                    }
                }
            }
            // Conditionals.
            "if" | "ie" => {
                let (taken, body) = self.condition(args_text);
                if name == "ie" {
                    self.conditions.push(taken);
                }
                self.run_conditional_body(taken, body, span);
            }
            "el" => {
                let taken = !self.conditions.pop().unwrap_or(false);
                let body = args_text.to_string();
                self.run_conditional_body(taken, body, span);
            }
            "ig" => self.skip_to_end(args_text),
            // Flow control inside a macro.
            "shift" => {
                let n = split_args(args_text).first().and_then(|a| a.parse::<usize>().ok()).unwrap_or(1);
                if let Some(frame) = self.frames.last_mut() {
                    for _ in 0..n {
                        if !frame.args.is_empty() {
                            frame.args.remove(0);
                        }
                    }
                }
            }
            "return" => {
                self.frames.pop();
            }
            "nop" => {
                let line = Line { text: args_text.to_string(), span };
                self.process(line);
            }
            // Bounded, because roff's own `.while` is not.
            "while" => self.run_while(args_text, span),
            // Things a terminal renderer has nothing to do with, and
            // which would otherwise reach the macro package as noise.
            "tm" | "tm1" | "ab" | "pm" | "pi" | "lf" | "fp" | "hw" | "hy" | "nh" | "hla" | "hlm" | "hcode"
            | "ss" | "cs" | "kern" | "lg" | "fam" | "char" | "rchar" | "tr" | "ec" | "eo" | "mc" | "psbb"
            | "pso" | "blm" | "wh" | "ch" | "dt" | "it" | "itc" | "em" | "di" | "da" | "box" | "boxa" | "asciify"
            | "unformat" | "output" | "device" | "devicem" | "warn" | "spreadwarn" | "msg" | "color" | "defcolor"
            | "gcolor" | "fcolor" | "break" | "continue" | "do" | "cp" | "cflags" | "class" => {}
            "so" | "mso" | "soquiet" | "msoquiet" => {
                self.note(format!("`.{name}` includes another file, which this parser does not follow"));
            }
            "TS" | "TE" => self.note("this page uses tbl tables, which are shown as plain text".to_string()),
            "EQ" | "EN" => self.note("this page uses eqn equations, which are shown as plain text".to_string()),
            "PS" | "PE" => self.note("this page uses pic drawings, which are skipped".to_string()),
            _ => {
                if let Some(body) = self.macros.get(name).cloned() {
                    self.invoke(name, body, args_text, span);
                } else {
                    let args = split_args(args_text);
                    self.events.push(Event::Request { name: name.to_string(), args, span });
                }
            }
        }
    }

    fn invoke(&mut self, name: &str, body: Vec<Line>, args_text: &str, span: Range<usize>) {
        if self.frames.len() >= MAX_DEPTH {
            self.note(format!("`.{name}` nests deeper than this parser follows"));
            return;
        }
        // The body's lines are re-spanned onto the invocation, which is
        // the only place in the source a reader could actually point at.
        let lines = body.into_iter().map(|l| Line { text: l.text, span: span.clone() }).collect();
        let args = split_args(args_text);
        self.frames.push(Frame { lines, pos: 0, args, name: name.to_string(), macro_body: true });
    }

    // `.de NAME [END]`: everything up to a line that is just `..` (or
    // `.END`) is the body, taken verbatim -- no expansion happens until
    // the macro is invoked.
    fn define_macro(&mut self, append: bool, args_text: &str) {
        let args = split_args(args_text);
        let Some(name) = args.first().cloned() else { return };
        let end = args.get(1).cloned().unwrap_or_else(|| ".".to_string());
        let body = self.take_body(&end);
        let entry = self.macros.entry(name).or_default();
        if !append {
            entry.clear();
        }
        entry.extend(body);
    }

    fn skip_to_end(&mut self, args_text: &str) {
        let end = split_args(args_text).first().cloned().unwrap_or_else(|| ".".to_string());
        self.take_body(&end);
    }

    // Lines up to the terminator, consumed from the current frame.
    fn take_body(&mut self, end: &str) -> Vec<Line> {
        let terminator = format!(".{end}");
        let mut body = Vec::new();
        while let Some(line) = self.next_line() {
            let trimmed = line.text.trim_end();
            if trimmed == terminator || (end == "." && trimmed == "..") {
                break;
            }
            body.push(line);
        }
        body
    }

    fn define_string(&mut self, append: bool, args_text: &str) {
        let text = args_text.trim_start();
        let (name, rest) = match text.find(|c: char| c.is_whitespace()) {
            Some(i) => (text[..i].to_string(), text[i..].trim_start()),
            None => (text.to_string(), ""),
        };
        if name.is_empty() {
            return;
        }
        // A leading `"` protects leading whitespace and is not content.
        let value = rest.strip_prefix('"').unwrap_or(rest).to_string();
        if append {
            self.strings.entry(name).or_default().push_str(&value);
        } else {
            self.strings.insert(name, value);
        }
    }

    fn set_register(&mut self, args_text: &str) {
        let args = split_args(args_text);
        let Some(name) = args.first() else { return };
        let Some(value) = args.get(1) else {
            self.registers.entry(name.clone()).or_insert(0);
            return;
        };
        // A leading sign makes it relative to the register's own value.
        let current = self.registers.get(name).copied().unwrap_or(0);
        let parsed = eval_number(value.trim_start_matches(['+', '-']));
        let next = match value.chars().next() {
            Some('+') => current + parsed,
            Some('-') => current - parsed,
            _ => eval_number(value),
        };
        self.registers.insert(name.clone(), next);
    }

    fn run_conditional_body(&mut self, taken: bool, body: String, span: Range<usize>) {
        let body = body.trim_start().to_string();
        // `\{` opens a block that runs to the matching `\}`, possibly
        // many lines later.
        if let Some(rest) = body.strip_prefix("\\{") {
            let mut lines = Vec::new();
            let rest = rest.strip_prefix('\n').unwrap_or(rest).trim_start_matches('\\');
            let first = rest.trim_start_matches('{').to_string();
            let mut depth = 1 + count_open(&first) - count_close(&first);
            if !first.trim().is_empty() {
                lines.push(Line { text: strip_braces(&first), span: span.clone() });
            }
            while depth > 0 {
                let Some(line) = self.next_line() else { break };
                depth += count_open(&line.text);
                depth -= count_close(&line.text);
                let text = strip_braces(&line.text);
                if depth > 0 || !text.trim().is_empty() {
                    lines.push(Line { text, span: line.span.clone() });
                }
            }
            if taken && !lines.is_empty() {
                if self.frames.len() >= MAX_DEPTH {
                    return;
                }
                let macro_body = self.frames.last().is_some_and(|f| f.macro_body);
                self.frames.push(Frame { lines, pos: 0, args: self.current_args(), name: "if".to_string(), macro_body });
            }
            return;
        }
        if taken && !body.trim().is_empty() {
            // A one-line body is processed as a line of its own, which
            // is how `.if n .SH NAME` works.
            self.process(Line { text: body, span });
        }
    }

    fn current_args(&self) -> Vec<String> {
        self.frames.last().map(|f| f.args.clone()).unwrap_or_default()
    }

    fn run_while(&mut self, args_text: &str, span: Range<usize>) {
        let (mut taken, body) = self.condition(args_text);
        let mut guard = 0;
        // The body is consumed once; re-running it is this loop's job.
        let saved_body = body.clone();
        while taken {
            guard += 1;
            if guard > 1000 {
                self.note("`.while` ran longer than this parser follows".to_string());
                return;
            }
            self.run_conditional_body(true, saved_body.clone(), span.clone());
            let (next, _) = self.condition(args_text);
            taken = next;
            if guard == 1 && saved_body.trim_start().starts_with("\\{") {
                // A multi-line while body was already consumed from the
                // source by the first pass; without the source to
                // re-read there is nothing to repeat.
                self.note("`.while` with a multi-line body runs once here".to_string());
                return;
            }
        }
    }

    // Returns whether the condition holds, and the body that follows it.
    fn condition(&mut self, args_text: &str) -> (bool, String) {
        let text = args_text.trim_start();
        let (cond, rest) = split_condition(text);
        (self.eval_condition(&cond), rest)
    }

    fn eval_condition(&mut self, cond: &str) -> bool {
        let cond = cond.trim();
        if let Some(rest) = cond.strip_prefix('!') {
            return !self.eval_condition(rest);
        }
        match cond.chars().next() {
            // Rendering to a terminal is nroff, never troff.
            Some('n') if cond.len() == 1 => true,
            Some('t') if cond.len() == 1 => false,
            Some('o') if cond.len() == 1 => true,
            Some('e') if cond.len() == 1 => false,
            Some('v') | Some('c') if cond.len() == 1 => false,
            Some('d') => {
                let name = cond[1..].trim();
                self.macros.contains_key(name) || self.strings.contains_key(name)
            }
            Some('r') => self.registers.contains_key(cond[1..].trim()),
            Some('F') | Some('S') => true,
            Some(delim) if !delim.is_alphanumeric() && !delim.is_whitespace() => {
                // `'a'b'` -- a string comparison in whatever delimiter
                // the page chose.
                let parts: Vec<&str> = cond[1..].split(delim).collect();
                if parts.len() >= 2 { parts[0] == parts[1] } else { false }
            }
            _ => eval_number(cond) != 0,
        }
    }

    // `\*x`, `\*(xx`, `\*[name]` string interpolation; `\n...` register
    // interpolation; `\$N` macro arguments. Everything else is left
    // exactly as written for the macro package to deal with.
    fn expand(&mut self, text: &str) -> String {
        self.expand_in(text, false)
    }

    fn expand_in(&mut self, text: &str, in_macro: bool) -> String {
        let mut out = String::new();
        let chars: Vec<char> = text.chars().collect();
        let mut i = 0;
        let mut rounds = 0;
        while i < chars.len() {
            if chars[i] != '\\' {
                out.push(chars[i]);
                i += 1;
                continue;
            }
            // Reading a macro body halves a doubled backslash, which is
            // how `\\$1` in a definition becomes an argument
            // substitution at invocation and not before.
            if in_macro && chars.get(i + 1) == Some(&'\\') {
                i += 1;
                continue;
            }
            let len = escape_len(&chars, i);
            match chars.get(i + 1) {
                Some('*') => {
                    let name = escape_argument(&chars, i + 2);
                    let value = self.strings.get(&name).cloned().unwrap_or_default();
                    rounds += 1;
                    // A string may itself contain interpolations; a
                    // bounded number of rounds keeps a self-referential
                    // one from looping.
                    out.push_str(&if rounds < 32 { self.expand_in(&value, in_macro) } else { value });
                }
                Some('n') => {
                    let name = escape_argument(&chars, i + 2);
                    let name = name.trim_start_matches(['+', '-']);
                    out.push_str(&self.registers.get(name).copied().unwrap_or(0).to_string());
                }
                Some('$') => {
                    let name = escape_argument(&chars, i + 2);
                    out.push_str(&self.macro_argument(&name));
                }
                _ => out.extend(&chars[i..(i + len).min(chars.len())]),
            }
            i += len;
        }
        out
    }

    fn macro_argument(&self, name: &str) -> String {
        let Some(frame) = self.frames.last() else { return String::new() };
        match name {
            "0" => frame.name.clone(),
            "*" => frame.args.join(" "),
            "@" => frame.args.iter().map(|a| format!("\"{a}\"")).collect::<Vec<_>>().join(" "),
            "#" => frame.args.len().to_string(),
            _ => match name.parse::<usize>() {
                Ok(n) if n >= 1 => frame.args.get(n - 1).cloned().unwrap_or_default(),
                _ => String::new(),
            },
        }
    }
}

fn count_open(s: &str) -> usize {
    s.matches("\\{").count()
}

fn count_close(s: &str) -> usize {
    s.matches("\\}").count()
}

fn strip_braces(s: &str) -> String {
    s.replace("\\{", "").replace("\\}", "")
}

// Splits a conditional's condition from the body that follows it. The
// condition ends at the first unquoted whitespace -- except for a
// delimited string comparison, which ends after its third delimiter.
fn split_condition(text: &str) -> (String, String) {
    let chars: Vec<char> = text.chars().collect();
    if chars.is_empty() {
        return (String::new(), String::new());
    }
    let mut i = 0;
    if chars[0] == '!' {
        i = 1;
    }
    let delim = chars.get(i).copied();
    if let Some(d) = delim
        && !d.is_alphanumeric()
        && !d.is_whitespace()
        && d != '\\'
        && d != '('
    {
        let mut seen = 0;
        let mut j = i;
        while j < chars.len() {
            if chars[j] == d {
                seen += 1;
                if seen == 3 {
                    j += 1;
                    break;
                }
            }
            j += if chars[j] == '\\' { escape_len(&chars, j) } else { 1 };
        }
        let cond: String = chars[..j].iter().collect();
        let rest: String = chars[j.min(chars.len())..].iter().collect();
        return (cond, rest.trim_start().to_string());
    }
    let mut j = i;
    let mut depth = 0;
    while j < chars.len() {
        match chars[j] {
            '(' => depth += 1,
            ')' => depth -= 1,
            c if c.is_whitespace() && depth <= 0 => break,
            '\\' => {
                j += escape_len(&chars, j);
                continue;
            }
            _ => {}
        }
        j += 1;
    }
    let cond: String = chars[..j].iter().collect();
    let rest: String = chars[j.min(chars.len())..].iter().collect();
    (cond, rest.trim_start().to_string())
}

// The one-char / `(xx` / `[name]` argument an escape takes.
fn escape_argument(chars: &[char], at: usize) -> String {
    match chars.get(at) {
        Some('(') => chars.iter().skip(at + 1).take(2).collect(),
        Some('[') => chars[at + 1..].iter().take_while(|&&c| c != ']' && c != '\n').collect(),
        Some(&c) => c.to_string(),
        None => String::new(),
    }
}

// roff number expressions: the arithmetic a page uses to compute
// indents. Scaling suffixes are dropped -- there is exactly one unit on
// a terminal, and pretending otherwise would produce worse numbers, not
// better ones.
pub fn eval_number(text: &str) -> i64 {
    let chars: Vec<char> = text.chars().collect();
    let mut pos = 0;
    parse_expr(&chars, &mut pos)
}

fn parse_expr(chars: &[char], pos: &mut usize) -> i64 {
    let mut left = parse_term(chars, pos);
    loop {
        skip_spaces(chars, pos);
        match chars.get(*pos) {
            Some('+') => {
                *pos += 1;
                left += parse_term(chars, pos);
            }
            Some('-') => {
                *pos += 1;
                left -= parse_term(chars, pos);
            }
            _ => return left,
        }
    }
}

fn parse_term(chars: &[char], pos: &mut usize) -> i64 {
    let mut left = parse_atom(chars, pos);
    loop {
        skip_spaces(chars, pos);
        match chars.get(*pos) {
            Some('*') => {
                *pos += 1;
                left *= parse_atom(chars, pos);
            }
            Some('/') => {
                *pos += 1;
                let d = parse_atom(chars, pos);
                left = if d == 0 { 0 } else { left / d };
            }
            Some('%') => {
                *pos += 1;
                let d = parse_atom(chars, pos);
                left = if d == 0 { 0 } else { left % d };
            }
            _ => return left,
        }
    }
}

fn parse_atom(chars: &[char], pos: &mut usize) -> i64 {
    skip_spaces(chars, pos);
    match chars.get(*pos) {
        Some('(') => {
            *pos += 1;
            let value = parse_expr(chars, pos);
            if chars.get(*pos) == Some(&')') {
                *pos += 1;
            }
            value
        }
        Some('-') => {
            *pos += 1;
            -parse_atom(chars, pos)
        }
        Some('+') => {
            *pos += 1;
            parse_atom(chars, pos)
        }
        _ => {
            let start = *pos;
            while chars.get(*pos).is_some_and(|c| c.is_ascii_digit()) {
                *pos += 1;
            }
            let digits: String = chars[start..*pos].iter().collect();
            // A scaling suffix (i, c, n, m, p, u, v, P) is consumed and
            // ignored.
            if chars.get(*pos).is_some_and(|c| "icnmpuvP".contains(*c)) {
                *pos += 1;
            }
            digits.parse().unwrap_or(0)
        }
    }
}

fn skip_spaces(chars: &[char], pos: &mut usize) {
    while chars.get(*pos).is_some_and(|c| *c == ' ' || *c == '\t') {
        *pos += 1;
    }
}

// Whether this line is a control line, and what follows the control
// character if so. `'` is the no-break control character and behaves the
// same for everything this cares about.
fn control_start(line: &str) -> Option<String> {
    let trimmed = line.trim_start_matches([' ', '\t']);
    let rest = trimmed.strip_prefix('.').or_else(|| trimmed.strip_prefix('\''))?;
    Some(rest.trim_start_matches([' ', '\t']).to_string())
}

fn request_name(rest: &str) -> (String, usize) {
    let mut end = 0;
    for (i, c) in rest.char_indices() {
        if c.is_whitespace() {
            end = i;
            break;
        }
        end = i + c.len_utf8();
    }
    (rest[..end].to_string(), end)
}

// A control line's arguments: whitespace-separated, except that a `"`
// opens one that runs to the next `"` -- which is how `.TH "GNU Coreutils"`
// stays one argument.
pub fn split_args(text: &str) -> Vec<String> {
    let chars: Vec<char> = text.chars().collect();
    let mut out = Vec::new();
    let mut i = 0;
    while i < chars.len() {
        while matches!(chars.get(i), Some(' ') | Some('\t')) {
            i += 1;
        }
        if i >= chars.len() {
            break;
        }
        let mut arg = String::new();
        if chars[i] == '"' {
            i += 1;
            while i < chars.len() {
                if chars[i] == '"' {
                    // `""` inside a quoted argument is one quote.
                    if chars.get(i + 1) == Some(&'"') {
                        arg.push('"');
                        i += 2;
                        continue;
                    }
                    i += 1;
                    break;
                }
                arg.push(chars[i]);
                i += 1;
            }
        } else {
            while i < chars.len() && !chars[i].is_whitespace() {
                if chars[i] == '\\' {
                    let len = escape_len(&chars, i);
                    arg.extend(&chars[i..(i + len).min(chars.len())]);
                    i += len;
                    continue;
                }
                arg.push(chars[i]);
                i += 1;
            }
        }
        out.push(arg);
    }
    out
}

// Everything from an unescaped `\"` to the end of the line is a comment.
fn strip_comment(line: &str) -> String {
    let chars: Vec<char> = line.chars().collect();
    let mut i = 0;
    while i < chars.len() {
        if is_comment_escape(&chars, i) {
            return chars[..i].iter().collect();
        }
        i += if chars[i] == '\\' { escape_len(&chars, i) } else { 1 };
    }
    line.to_string()
}

// Byte offsets into char offsets, since every span in this codebase is
// in characters.
fn char_span(source: &str, start: usize, end: usize) -> Range<usize> {
    let start_chars = source[..start].chars().count();
    let len = source[start..end].chars().count();
    start_chars..start_chars + len
}
